### PR TITLE
Issue/st 5154 android rounding

### PR DESCRIPTION
**Pull request by ChrisLFieldsII**
Adds native code for android to round native video view

### CODE REVIEW

**Comment by pixelknitter** [comment]
Does this not impact the full screen view as well? Curious why the react native view wrapping the android video doesn't respect the styling. 🤔

**Comment by pixelknitter** [comment]
We might leave a comment here to note this is a workaround fix that isn't ideal as it defers styling changes to native.

Certainly fine for launch if it doesn't impact other views we're using.

**Comment by ChrisLFieldsII** [comment]
> Does this not impact the full screen view as well? Curious why the react native view wrapping the android video doesn't respect the styling. 🤔

I wondered the same but fullscreen was fine on my test device. Please let me know if you notice otherwise!

**Comment by ChrisLFieldsII** [comment]
> We might leave a comment here to note this is a workaround fix that isn't ideal as it defers styling changes to native.
> 
> Certainly fine for launch if it doesn't impact other views we're using.

I think the fix is perfect for our use case and knowing that twilio is going away within 6 months. No need to do anything fancier with passing stuff from JS unless of course we find ourselves having to do many native stylings like this

**Review by dfinn — APPROVED** [review]
Tested and looks good! Strange that the borderRadius doesn't get respected, but as you guys mentioned maybe when we switch over to the Chime SDK that would get fixed anyway, so this works for now!

**Pull request merged**
